### ISSUE TITLE
Figure out best treatment of paired reads

### ISSUE THREAD

**Issue by BioWilko** [snowy-leopard/scylla#8]
Lots of paired reads are currently being dropped by fastp due to not having sufficient overlap (some libraries might have 0% overlap), need to investigate best way to solve this, some options include:

* Interleave paired reads into one file after standard fastp filtering then drop pairs from the taxon binned files which are assigned to different taxa during extract reads (binned fastqs should also be interleaved, effort will need to be taken to ensure interleaving is done robustly during binning)
* Link read pairs with N linker, run them through kraken, then extract pairs into separate taxon files from the raw 1/2 files based on the N-linked merged reads

I'm leaning towards option 1, some people might complain about having interleaved fastq files but it does mean that we will have consistent fields for samples regardless of platform and the number of pairs dropped from the binned fastqs should be pretty minimal in most cases, we will have to write logic that accounts for differing taxonomic levels like: read_1 is in escherichia, read_2 is in escherichia coli so the pair is binned in the highest shared taxonomic level below some defined taxonomic level (I assume there's already code that does similar sorts of things during taxon binning)

**Comment by rmcolq** [comment]
We now:
1. Run fastp on paired reads separately
2. Then concat paired reads with a `|` for kraken only (natively handled by kraken)
3. Use separate read files for all other purposes
